---
- hosts: centos
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
  - name: replace PasswordAuthentication line
    lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        #check_mode: yes
        backup: yes
  - name: replace PermitRootLogin line
    lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PermitRootLogin"      
        line: "PermitRootLogin no"
        state: present
        #check_mode: yes
  - name: replace AllowUsers line
    lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "AllowUsers root"
        line: "#AllowUsers root"
        state: present
        #check_mode: yes

