---
- hosts: sec_test
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
    - name: Number of emails in exim queue
      command: exim -bpc
      register: result
    - set_fact:
        count: "{{ result.stdout }}"
    - debug: var="result.stdout"
    - debug: var="ansible_hostname"
    - name: Send email to Email manager for high freeze count
      mail:
        host: mail.iranserver.com
        port: 25
        username: cxs@iranserver.com
        password: QxGPyE7L
        from: cxs@iranserver.com
        to: <cxs.alert@iranserver.com>
        subject: Warning  >>  More than 1000 emails in  "{{ ansible_hostname }}"  queue
        body: There are  {{ result.stdout }}  emails in queue of  "{{ ansible_hostname }}"
      when: "'count >= 1000'"
