---
- hosts: webservers
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
    - name: freshclam command
      command: freshclam
      

    - name: Show result
      debug:
        msg: "clamAV has been updated"
      when: result is changed
