---
- hosts: sec_test
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
    - name: freshclam command
      command: freshclam
      

#    - name: Show result
#      debug:
#        msg: "iptable rules added to this server"
#      when: result is changed
