---
- hosts: DA
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
  - name: check enable-cgi
    lineinfile:
     path: /usr/local/directadmin/custombuild/custom/ap2/configure.apache
     line: "disable-cgi"
     state: present
    check_mode: yes
    register: result
    ignore_errors: True
  - name: cgi enabled
    debug:
      msg: "CGI is ENABLE on this server"
    when: result is changed
