---
- hosts: webservers
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
    - name: Add iptable rules
      command: "{{ item }}"
      loop:
        - iptables -I OUTPUT 1 -p tcp -m tcp --dport 80 -m string --string "xmlrpc.php" --algo kmp --to 1024 -j LOG --log-prefix "Potential WP Attack detected" --log-level 1 --log-uid
        - iptables -I OUTPUT 1 -p tcp -m tcp --dport 80 -m string --string "wp-login.php" --algo kmp --to 1024 -j LOG --log-prefix "Potential WP Attack detected" --log-level 1 --log-uid
        - iptables -I OUTPUT 1 -p tcp -m tcp --dport 80 -m string --string "administrator" --algo kmp --to 1024 -j LOG --log-prefix "Potential Joomla Attack detected" --log-level 1 --log-uid
        - iptables -I OUTPUT 1 -p tcp -m tcp --dport 443 -m string --string "xmlrpc.php" --algo kmp --to 1024 -j LOG --log-prefix "Potential WP Attack detected" --log-level 1 --log-uid
        - iptables -I OUTPUT 1 -p tcp -m tcp --dport 443 -m string --string "wp-login.php" --algo kmp --to 1024 -j LOG --log-prefix "Potential WP Attack detected" --log-level 1 --log-uid
        - iptables -I OUTPUT 1 -p tcp -m tcp --dport 443 -m string --string "administrator" --algo kmp --to 1024 -j LOG --log-prefix "Potential Joomla Attack detected" --log-level 1 --log-uid

    - name: Show result
      debug:
        msg: "iptable rules added to this server"
      when: result is changed
