---
- hosts: sec_test
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
    - name: remove old net.netfilter lines
      lineinfile:
        path: /etc/hosts.allow
        regexp: "SSHD" 
        state: absent
        backup: yes
    - name: add IranServer IPs block
      blockinfile:
        path: /etc/hosts.allow
        marker: "<!-- {mark} AWX MANAGED BLOCK -->"
        block: |
          SSHD : 2.180.24.28 : ALLOW
          SSHD : 2.180.20.174 : ALLOW
          SSHD : 2.180.21.117 : ALLOW
          SSHD : 2.180.37.185 : ALLOW
          SSHD : 2.180.9.177 : ALLOW
          SSHD : 109.125.139.91 : ALLOW
          SSHD : 109.125.133.245 : ALLOW
          SSHD : 109.125.135.62 : ALLOW
          SSHD : 109.125.138.254 : ALLOW
          SSHD : 185.4.28.202 : ALLOW
          SSHD : 2.180.239.116 : ALLOW
          SSHD : tunnel.irandns.com : ALLOW

   
#    - name: Show result
#      debug:
#        msg: "configurations has been added to conf-perm file"
#      when: result is changed
