---
- hosts: centos
  gather_facts: False
  #connection: local

  tasks:
    - name: ping 8.8.8.8
      shell: ping -c 4 4.2.2.4
      ignore_errors: true
      register: res
    - name: Show result ping 8.8.8.8
      debug:
        msg: "{{ res['stdout_lines'] }}"         
    
    - name: ping {{ dest_node }}
      shell: ping -c 4 {{ dest_node }}
      ignore_errors: true      
      register: res
    - name: Show result ping {{ dest_node }}
      debug:
        msg: "{{ res['stdout_lines'] }}"       

