---
- hosts: DA
  gather_facts: False
  #connection: local

  tasks:
    - name: Internet access check
      shell: ping -c 4 8.8.8.8
      ignore_errors: true
      register: res
    - name: Show result
      debug:
        msg: "{{ res['stdout_lines'] }}"         
    
#    - name: ping {{ dest_node }}
#      shell: ping -c 4 {{ dest_node }}
#      ignore_errors: true      
#      register: res
#    - name: Show result ping {{ dest_node }}
#      debug:
#        msg: "{{ res['stdout_lines'] }}"       

