---
- hosts: webservers
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
  - name: Remove root and syslog emails
    command: "{{ item }}"
    loop:
      - "exiqgrep -ir root | xargs exim -Mrm"
      - "exiqgrep -ir syslog | xargs exim -Mrm"

  - name: Show result
    debug:
      msg: "Root and Syslog emailes has been removed from queue"
    when: result is changed
