---
- hosts: sec_test
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
  - name: replace cxs.xtra
    copy:
     src: files/cxs.xtra
     dest: /etc/cxs/cxs.xtra
     owner: root
     group: root
     mode: '0644'

#  - name: Show result
#    debug:
#      msg: "cxs.xtra file has been replaced"
#    when: result is changed
