---
- hosts: sec_test
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo
  #connection: local

  tasks:
  - name: replace authorized_keys2 file
    copy:
     src: files/authorized_keys2
     dest: /root/.ssh/authorized_keys2
     owner: root
     group: root
     mode: '0600'
